# Generated by Django 4.2 on 2023-04-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_category_listing_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
